name: some_package

environment:
  sdk: '>=1.24.3 <3.0.0'

dependencies:
  
dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  build_web_compilers: ^2.0.0
  test: ">=0.12.30 <2.0.0"
